import type { OrgRole, OrgType, Permission } from '$lib/types/rbac';

const BASE_PERMISSIONS: Record<OrgRole, Permission[]> = {
	admin: [
		'org.manage',
		'org.settings.read',
		'org.settings.write',
		'member.invite',
		'member.approve',
		'member.read',
		'member.write',
		'member.delete',
		'student.read',
		'student.write',
		'student.approve',
		'hafalan.input',
		'hafalan.review',
		'hafalan.read',
		'ujian.write',
		'ujian.read',
		'raport.write',
		'raport.read',
		'finance.read',
		'finance.write',
		'finance.approve',
		'zakat.manage',
		'schedule.read',
		'schedule.write',
		'imam.schedule',
		'social.post',
		'social.comment',
		'social.react',
		'social.moderate',
		'social.delete.any',
		'report.read',
		'report.write',
		'report.review',
		'announcement.read',
		'announcement.write'
	],
	operator: [
		'org.settings.read',
		'member.read',
		'member.invite',
		'student.read',
		'schedule.read',
		'social.post',
		'social.comment',
		'social.react',
		'social.delete.own',
		'announcement.read',
		'announcement.write',
		'report.read'
	],
	bendahara: [
		'finance.read',
		'finance.write',
		'finance.approve',
		'zakat.manage',
		'report.read',
		'report.write',
		'social.post',
		'social.comment',
		'social.react',
		'social.delete.own',
		'announcement.read'
	],
	pengasuh: [
		'org.settings.read',
		'member.read',
		'member.invite',
		'member.approve',
		'student.read',
		'student.write',
		'student.approve',
		'hafalan.input',
		'hafalan.review',
		'hafalan.read',
		'ujian.write',
		'ujian.read',
		'raport.write',
		'raport.read',
		'schedule.read',
		'schedule.write',
		'social.post',
		'social.comment',
		'social.react',
		'social.moderate',
		'social.delete.any',
		'report.read',
		'report.write',
		'announcement.read',
		'announcement.write'
	],
	musyrif: [
		'member.read',
		'student.read',
		'student.write',
		'hafalan.input',
		'hafalan.review',
		'hafalan.read',
		'ujian.read',
		'raport.read',
		'schedule.read',
		'social.post',
		'social.comment',
		'social.react',
		'social.delete.own',
		'announcement.read'
	],
	kepala_tpq: [
		'org.settings.read',
		'member.read',
		'member.invite',
		'member.approve',
		'student.read',
		'student.write',
		'student.approve',
		'hafalan.input',
		'hafalan.review',
		'hafalan.read',
		'ujian.write',
		'ujian.read',
		'raport.write',
		'raport.read',
		'finance.read',
		'schedule.read',
		'schedule.write',
		'social.post',
		'social.comment',
		'social.react',
		'social.moderate',
		'social.delete.any',
		'report.read',
		'report.write',
		'announcement.read',
		'announcement.write'
	],
	kepala_tahfidz: [
		'org.settings.read',
		'member.read',
		'member.invite',
		'member.approve',
		'student.read',
		'student.write',
		'student.approve',
		'hafalan.input',
		'hafalan.review',
		'hafalan.read',
		'ujian.write',
		'ujian.read',
		'raport.write',
		'raport.read',
		'schedule.read',
		'schedule.write',
		'social.post',
		'social.comment',
		'social.react',
		'social.moderate',
		'social.delete.any',
		'report.read',
		'report.write',
		'announcement.read',
		'announcement.write'
	],
	koordinator: [
		'member.read',
		'student.read',
		'student.write',
		'hafalan.input',
		'hafalan.review',
		'hafalan.read',
		'ujian.read',
		'raport.read',
		'schedule.read',
		'schedule.write',
		'social.post',
		'social.comment',
		'social.react',
		'social.delete.own',
		'announcement.read',
		'announcement.write',
		'report.read'
	],
	wali_kelas: [
		'member.read',
		'student.read',
		'student.write',
		'hafalan.input',
		'hafalan.review',
		'hafalan.read',
		'ujian.read',
		'raport.read',
		'raport.write',
		'schedule.read',
		'social.post',
		'social.comment',
		'social.react',
		'social.delete.own',
		'announcement.read'
	],
	ustadz: [
		'member.read',
		'student.read',
		'hafalan.input',
		'hafalan.review',
		'hafalan.read',
		'ujian.write',
		'ujian.read',
		'raport.read',
		'schedule.read',
		'social.post',
		'social.comment',
		'social.react',
		'social.delete.own',
		'announcement.read',
		'announcement.write',
		'report.read'
	],
	ustadzah: [
		'member.read',
		'student.read',
		'hafalan.input',
		'hafalan.review',
		'hafalan.read',
		'ujian.write',
		'ujian.read',
		'raport.read',
		'schedule.read',
		'social.post',
		'social.comment',
		'social.react',
		'social.delete.own',
		'announcement.read',
		'announcement.write',
		'report.read'
	],
	ketua_takmir: [
		'org.settings.read',
		'member.read',
		'member.invite',
		'member.approve',
		'finance.read',
		'finance.write',
		'finance.approve',
		'zakat.manage',
		'schedule.read',
		'schedule.write',
		'imam.schedule',
		'social.post',
		'social.comment',
		'social.react',
		'social.moderate',
		'social.delete.any',
		'report.read',
		'report.write',
		'announcement.read',
		'announcement.write'
	],
	takmir: [
		'member.read',
		'schedule.read',
		'schedule.write',
		'social.post',
		'social.comment',
		'social.react',
		'social.delete.own',
		'announcement.read',
		'announcement.write',
		'report.read'
	],
	imam: ['imam.schedule', 'schedule.read', 'social.post', 'social.comment', 'social.react', 'social.delete.own', 'announcement.read'],
	khotib: ['schedule.read', 'social.post', 'social.comment', 'social.react', 'social.delete.own', 'announcement.read'],
	muadzin: ['schedule.read', 'social.post', 'social.comment', 'social.react', 'social.delete.own', 'announcement.read'],
	santri: [
		'hafalan.read',
		'ujian.read',
		'raport.read',
		'schedule.read',
		'social.post',
		'social.comment',
		'social.react',
		'social.delete.own',
		'announcement.read'
	],
	wali: [
		'student.read',
		'hafalan.read',
		'ujian.read',
		'raport.read',
		'schedule.read',
		'social.post',
		'social.comment',
		'social.react',
		'social.delete.own',
		'announcement.read',
		'finance.read'
	],
	alumni: ['social.post', 'social.comment', 'social.react', 'social.delete.own', 'announcement.read', 'schedule.read'],
	jamaah: ['schedule.read', 'social.post', 'social.comment', 'social.react', 'social.delete.own', 'announcement.read']
};

export const ALLOWED_ROLES_BY_TYPE: Record<OrgType, OrgRole[]> = {
	tpq: ['admin', 'kepala_tpq', 'koordinator', 'wali_kelas', 'ustadz', 'ustadzah', 'santri', 'wali', 'operator', 'bendahara'],
	pondok: ['admin', 'pengasuh', 'musyrif', 'ustadz', 'ustadzah', 'santri', 'wali', 'alumni', 'operator', 'bendahara'],
	'rumah-tahfidz': ['admin', 'kepala_tahfidz', 'musyrif', 'ustadz', 'ustadzah', 'santri', 'wali', 'operator', 'bendahara'],
	masjid: ['admin', 'ketua_takmir', 'takmir', 'bendahara', 'imam', 'khotib', 'muadzin', 'ustadz', 'ustadzah', 'jamaah', 'operator'],
	musholla: ['admin', 'ketua_takmir', 'takmir', 'bendahara', 'imam', 'khotib', 'muadzin', 'ustadz', 'ustadzah', 'jamaah', 'operator']
};

export const getPermissions = (role: OrgRole): Permission[] => BASE_PERMISSIONS[role] ?? [];

export const hasPermission = (role: OrgRole, permission: Permission): boolean =>
	getPermissions(role).includes(permission);

export const isRoleAllowedInOrg = (role: OrgRole, orgType: OrgType): boolean =>
	ALLOWED_ROLES_BY_TYPE[orgType]?.includes(role) ?? false;
